[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "http-server"
version = "0.0.1"

[project.scripts]
serv = "src.server:run"

[tool.setuptools.packages.find]
where = ["."]